### PR TITLE
Focuswriter - includes libhunspell

### PR DESCRIPTION
**Pull request by funnylookinhat**
I could be crazy - but seems that simple.

### CODE REVIEW

**Comment by funnylookinhat** [comment]
Err - solves #32

**Comment by Justinzobel** [comment]
Hey @funnylookinhat we need the package.yml file and we need one package per commit please, dependency (hunspell first)

**Comment by funnylookinhat** [comment]
Ah shoot - yeah that's right.  OK - Trying again.

**Comment by Justinzobel** [comment]
No worries, you should see the amount of mistakes I made when I started packaging (still make some much to the detriment of ikey's sanity).

**Pull request closed without merging**
