### PR TITLE
libhunspell

### PR DESCRIPTION
**Pull request by funnylookinhat**
libhunspell - required for building focuswriter - #32

### CODE REVIEW

**Comment by funnylookinhat** [comment]
Let me know if you need anything changed on this PR and I'll update before you merge.

**Comment by Justinzobel** [comment]
Looks good, not sure about the licenses but we can fix that up after, if there's multiple licenses I usually do:
license:
    - gpl
    - lgpl3 etc

**Comment by Justinzobel** [comment]
Oh and try match licenses to the identifier on here: http://spdx.org/licenses/ ie GPL-3.0 etc.

**Comment by ikeydoherty** [comment]
This wasn't ready for merging @Justinzobel - apart from the license issue (you are correct, one per line) - this carries static archives that haven't been discussed yet. Also note that the source name does not match the upstream name.

**Comment by ikeydoherty** [comment]
I shall fix these parts myself after work as I now need to add a migration path for the renaming..

**Comment by Justinzobel** [comment]
I agree I missed a few things but shouldn't need to make an upgrade path @ikeydoherty as nothing uses it yet, right?

**Pull request merged**
