### PR TITLE
[Update] Curl -> 7.41.0

### PR DESCRIPTION
**Pull request by ovr**

### CODE REVIEW

**Comment by ovr** [comment]
ping @ikeydoherty

**Comment by Justinzobel** [comment]
Pull requests are no longer accepted, please use git send-email to send your commits to packaging@evolve-os.com

e.g.
git add .
git commit
git send-email -1

**Comment by ovr** [comment]
@Justinzobel Why?

GitHub is awesome git web gui, and it's easy to merge

**Comment by ikeydoherty** [comment]
This problem is two fold..

1) I see no actual reason to update curl - can you elaborate? :)
2) The README specifically says we use the mailing list.. GitHub is poor at showing extensive diffs, hides the details of the commiter, and one cannot control the merge policy when hitting "Merge pull request"

**Comment by JoshStrobl** [comment]
I sent a patch in to update CURL. CURL 7.41.0 addresses some SSL issues, IPV6 issues, and provides re-implementations of some hashing like md5.

**Comment by ikeydoherty** [comment]
Merging. Thanks :)

**Pull request merged**
