### PR TITLE
focuswriter

### PR DESCRIPTION
**Pull request by funnylookinhat**
focuswriter - #32

### CODE REVIEW

**Comment by funnylookinhat** [comment]
Let me know if you need anything changed on this PR and I'll update before you merge.

**Comment by Justinzobel** [comment]
As discussed in other PR please update license based on http://spdx.org/licenses/ and then we can merge :D

**Comment by funnylookinhat** [comment]
How does it look now?

**Comment by Justinzobel** [comment]
Missing  pkgconfig(hunspell) dependency.

**Comment by ikeydoherty** [comment]
I've manually imported it as:
https://git.solus-project.com/packages/focuswriter/commit/?id=523d687722735d1018f260867bc1c26c3bb28af3

Cheers! :]

**Comment by funnylookinhat** [comment]
Ah awesome - I'll talk to you in a week or so when I'm off of vacation about becoming a maintainer for it so you don't have to worry about that one.

**Pull request closed without merging**
